### Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Rishabh Sharma",
  "email": "rishabh@example.com",
  "password": "mypassword123"
}

###login an existing user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "rishabh@example.com",
    "password": "mypassword123"
}

###creating shortLinks
POST http://localhost:5000/api/shorten
Content-Type: application/json

{
    "longUrl": "https://www.geeksforgeeks.org/"
}
